// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnfLRnUsdG8WuGZyxbE9aG7b7LU9kBMV4',
    appId: '1:275045829119:web:1f1fb2354cc5b7ccca7fca',
    messagingSenderId: '275045829119',
    projectId: 'car-app-93a1c',
    authDomain: 'car-app-93a1c.firebaseapp.com',
    storageBucket: 'car-app-93a1c.firebasestorage.app',
    measurementId: 'G-BR8KPB7VXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmMC3aJqZKwg01SPCANyqibJqst7YOryo',
    appId: '1:275045829119:android:ffbdddd1f22178ffca7fca',
    messagingSenderId: '275045829119',
    projectId: 'car-app-93a1c',
    storageBucket: 'car-app-93a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5ElIYsGDs39AGj9I-pBRT9pkPfBwbPk',
    appId: '1:275045829119:ios:1f82ad88a780bd6cca7fca',
    messagingSenderId: '275045829119',
    projectId: 'car-app-93a1c',
    storageBucket: 'car-app-93a1c.firebasestorage.app',
    iosBundleId: 'com.abdo.carapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv_GcBk1EuA1wF1dMrbNS-hOW4Jq--mzk',
    appId: '1:200130945805:ios:a1f9617740d46eb7bdc644',
    messagingSenderId: '200130945805',
    projectId: 'car-app-460ca',
    storageBucket: 'car-app-460ca.appspot.com',
    iosBundleId: 'com.example.carApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWzkmg6gzGRLoZBeRCia-BhemhcYXGES8',
    appId: '1:200130945805:web:d0c9c42b5ee8647cbdc644',
    messagingSenderId: '200130945805',
    projectId: 'car-app-460ca',
    authDomain: 'car-app-460ca.firebaseapp.com',
    storageBucket: 'car-app-460ca.appspot.com',
    measurementId: 'G-2K4XHLH7EQ',
  );

}
